name: timerapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.1.0
  audioplayers: ^5.2.1
  logging: ^1.2.0
  audio_session: ^0.1.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/alarm/alarm.mp3
    - assets/sounds/
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # 여기에 아이콘 이미지 경로 지정
  min_sdk_android: 21 # 안드로이드 최소 SDK 버전
  # 적응형 아이콘을 원한다면:
  adaptive_icon_background: "#ffffff" # 배경색
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png" # 전경 이미지